import React from 'react';
import { Metadata } from 'next';
import Footer from '@/components/layouts/footer';
import Header from '@/components/layouts/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <Header />
      <div className="-mt-16 pt-16">{children}</div>
      <Footer />
    </main>
  );
}
